module.exports = {
    role_admin: 1,
    role_student: 2,
    role_class: 3,
    role_union: 4,
    status_act_wait : 1,
    status_act_end: 3,
    status_act_accept: 2,
    status_act_reject: 4,
    status_act_ongoing: 5 ,
    object_create: 1,
    object_student: 2,
    status_active :1,
    status_inactive:2,
    secret_key  : "nhom2ptithcm",
};